################################################################################
# Automatically-generated file. Do not edit!
################################################################################

OBJ_SRCS := 
ASM_SRCS := 
C_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
EXECUTABLES := 
OBJS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
App/src \
Bsp \
Bsp/src \
Library/CMSIS/DAP/Firmware/Examples/LPC-Link-II/RTE/CMSIS \
Library/CMSIS/DAP/Firmware/Examples/LPC-Link-II/RTE/Device/LPC4320_Cortex-M4 \
Library/CMSIS/DAP/Firmware/Examples/LPC-Link-II/RTE/USB \
Library/CMSIS/DAP/Firmware/Examples/LPC-Link-II \
Library/CMSIS/DAP/Firmware/Examples/XMC4200/RTE/CMSIS \
Library/CMSIS/DAP/Firmware/Examples/XMC4200/RTE/Device/XMC4200-Q48x256 \
Library/CMSIS/DAP/Firmware/Examples/XMC4200/RTE/USB \
Library/CMSIS/DAP/Firmware/Examples/XMC4200 \
Library/CMSIS/DAP/Firmware/Source \
Library/CMSIS/DAP/Firmware/Template/MDK5 \
Library/CMSIS/DSP_Lib/Examples/arm_class_marks_example/ARM/RTE/Device/ARMCM0 \
Library/CMSIS/DSP_Lib/Examples/arm_class_marks_example/ARM/RTE/Device/ARMCM3 \
Library/CMSIS/DSP_Lib/Examples/arm_class_marks_example/ARM/RTE/Device/ARMCM4_FP \
Library/CMSIS/DSP_Lib/Examples/arm_class_marks_example/ARM/RTE/Device/ARMCM7_SP \
Library/CMSIS/DSP_Lib/Examples/arm_class_marks_example/ARM \
Library/CMSIS/DSP_Lib/Examples/arm_class_marks_example/GCC/Startup \
Library/CMSIS/DSP_Lib/Examples/arm_class_marks_example/GCC \
Library/CMSIS/DSP_Lib/Examples/arm_convolution_example/ARM/RTE/Device/ARMCM0 \
Library/CMSIS/DSP_Lib/Examples/arm_convolution_example/ARM/RTE/Device/ARMCM3 \
Library/CMSIS/DSP_Lib/Examples/arm_convolution_example/ARM/RTE/Device/ARMCM4_FP \
Library/CMSIS/DSP_Lib/Examples/arm_convolution_example/ARM/RTE/Device/ARMCM7_SP \
Library/CMSIS/DSP_Lib/Examples/arm_convolution_example/ARM \
Library/CMSIS/DSP_Lib/Examples/arm_convolution_example/GCC/Startup \
Library/CMSIS/DSP_Lib/Examples/arm_convolution_example/GCC \
Library/CMSIS/DSP_Lib/Examples/arm_dotproduct_example/ARM/RTE/Device/ARMCM0 \
Library/CMSIS/DSP_Lib/Examples/arm_dotproduct_example/ARM/RTE/Device/ARMCM3 \
Library/CMSIS/DSP_Lib/Examples/arm_dotproduct_example/ARM/RTE/Device/ARMCM4_FP \
Library/CMSIS/DSP_Lib/Examples/arm_dotproduct_example/ARM/RTE/Device/ARMCM7_SP \
Library/CMSIS/DSP_Lib/Examples/arm_dotproduct_example/ARM \
Library/CMSIS/DSP_Lib/Examples/arm_dotproduct_example/GCC/Startup \
Library/CMSIS/DSP_Lib/Examples/arm_dotproduct_example/GCC \
Library/CMSIS/DSP_Lib/Examples/arm_fft_bin_example/ARM/RTE/Device/ARMCM0 \
Library/CMSIS/DSP_Lib/Examples/arm_fft_bin_example/ARM/RTE/Device/ARMCM3 \
Library/CMSIS/DSP_Lib/Examples/arm_fft_bin_example/ARM/RTE/Device/ARMCM4_FP \
Library/CMSIS/DSP_Lib/Examples/arm_fft_bin_example/ARM/RTE/Device/ARMCM7_SP \
Library/CMSIS/DSP_Lib/Examples/arm_fft_bin_example/ARM \
Library/CMSIS/DSP_Lib/Examples/arm_fft_bin_example/GCC/Startup \
Library/CMSIS/DSP_Lib/Examples/arm_fft_bin_example/GCC \
Library/CMSIS/DSP_Lib/Examples/arm_fir_example/ARM/RTE/Device/ARMCM0 \
Library/CMSIS/DSP_Lib/Examples/arm_fir_example/ARM/RTE/Device/ARMCM3 \
Library/CMSIS/DSP_Lib/Examples/arm_fir_example/ARM/RTE/Device/ARMCM4_FP \
Library/CMSIS/DSP_Lib/Examples/arm_fir_example/ARM/RTE/Device/ARMCM7_SP \
Library/CMSIS/DSP_Lib/Examples/arm_fir_example/ARM \
Library/CMSIS/DSP_Lib/Examples/arm_graphic_equalizer_example/ARM/RTE/Device/ARMCM0 \
Library/CMSIS/DSP_Lib/Examples/arm_graphic_equalizer_example/ARM/RTE/Device/ARMCM3 \
Library/CMSIS/DSP_Lib/Examples/arm_graphic_equalizer_example/ARM/RTE/Device/ARMCM4_FP \
Library/CMSIS/DSP_Lib/Examples/arm_graphic_equalizer_example/ARM/RTE/Device/ARMCM7_SP \
Library/CMSIS/DSP_Lib/Examples/arm_graphic_equalizer_example/ARM \
Library/CMSIS/DSP_Lib/Examples/arm_linear_interp_example/ARM/RTE/Device/ARMCM0 \
Library/CMSIS/DSP_Lib/Examples/arm_linear_interp_example/ARM/RTE/Device/ARMCM3 \
Library/CMSIS/DSP_Lib/Examples/arm_linear_interp_example/ARM/RTE/Device/ARMCM4_FP \
Library/CMSIS/DSP_Lib/Examples/arm_linear_interp_example/ARM/RTE/Device/ARMCM7_SP \
Library/CMSIS/DSP_Lib/Examples/arm_linear_interp_example/ARM \
Library/CMSIS/DSP_Lib/Examples/arm_matrix_example/ARM/RTE/Device/ARMCM0 \
Library/CMSIS/DSP_Lib/Examples/arm_matrix_example/ARM/RTE/Device/ARMCM3 \
Library/CMSIS/DSP_Lib/Examples/arm_matrix_example/ARM/RTE/Device/ARMCM4_FP \
Library/CMSIS/DSP_Lib/Examples/arm_matrix_example/ARM/RTE/Device/ARMCM7_SP \
Library/CMSIS/DSP_Lib/Examples/arm_matrix_example/ARM \
Library/CMSIS/DSP_Lib/Examples/arm_signal_converge_example/ARM/RTE/Device/ARMCM0 \
Library/CMSIS/DSP_Lib/Examples/arm_signal_converge_example/ARM/RTE/Device/ARMCM3 \
Library/CMSIS/DSP_Lib/Examples/arm_signal_converge_example/ARM/RTE/Device/ARMCM4_FP \
Library/CMSIS/DSP_Lib/Examples/arm_signal_converge_example/ARM/RTE/Device/ARMCM7_SP \
Library/CMSIS/DSP_Lib/Examples/arm_signal_converge_example/ARM \
Library/CMSIS/DSP_Lib/Examples/arm_sin_cos_example/ARM/RTE/Device/ARMCM0 \
Library/CMSIS/DSP_Lib/Examples/arm_sin_cos_example/ARM/RTE/Device/ARMCM3 \
Library/CMSIS/DSP_Lib/Examples/arm_sin_cos_example/ARM/RTE/Device/ARMCM4_FP \
Library/CMSIS/DSP_Lib/Examples/arm_sin_cos_example/ARM/RTE/Device/ARMCM7_SP \
Library/CMSIS/DSP_Lib/Examples/arm_sin_cos_example/ARM \
Library/CMSIS/DSP_Lib/Examples/arm_variance_example/ARM/RTE/Device/ARMCM0 \
Library/CMSIS/DSP_Lib/Examples/arm_variance_example/ARM/RTE/Device/ARMCM3 \
Library/CMSIS/DSP_Lib/Examples/arm_variance_example/ARM/RTE/Device/ARMCM4_FP \
Library/CMSIS/DSP_Lib/Examples/arm_variance_example/ARM/RTE/Device/ARMCM7_SP \
Library/CMSIS/DSP_Lib/Examples/arm_variance_example/ARM \
Library/CMSIS/DSP_Lib/Source/BasicMathFunctions \
Library/CMSIS/DSP_Lib/Source/CommonTables \
Library/CMSIS/DSP_Lib/Source/ComplexMathFunctions \
Library/CMSIS/DSP_Lib/Source/ControllerFunctions \
Library/CMSIS/DSP_Lib/Source/FastMathFunctions \
Library/CMSIS/DSP_Lib/Source/FilteringFunctions \
Library/CMSIS/DSP_Lib/Source/MatrixFunctions \
Library/CMSIS/DSP_Lib/Source/StatisticsFunctions \
Library/CMSIS/DSP_Lib/Source/SupportFunctions \
Library/CMSIS/DSP_Lib/Source/TransformFunctions \
Library/CMSIS/Driver/DriverTemplates \
Library/Device/Nuvoton/Mini58Series/Source \
Library/StdDriver/src \
Project/obj \
utils/src \

